---
title: "Simulation"
author: "Bohan Zhu"
date: "2025-11-11"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy = TRUE)
```

Load key packages and source necessary files

```{r}
library(tidyverse)

source("sim_mean_sd.R")
```

```{r,include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  fig.retina = 2,
  dpi = 320
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


We can "simulate" by running our function

```{r}
sim_mean_sd(n_subj = 400)
```

can I "verify" the central limit theorem?

```{r}
output = vector("list", length = 100)

for (i in 1:100){
  output[[i]] = sim_mean_sd(30)
}

output |> 
  bind_rows() |> 
  ggplot(aes(x = mu_hat)) +
  geom_density()
```

Try to repeat with a map statement
```{r}
sim_results_df =
  expand_grid(
    iter = 1:100,
    sample_size = c(30, 60, 90, 120)
  ) |> 
  mutate(
    results = map(sample_size, sim_mean_sd)
  ) |> 
  unnest(results)
```

